spring.application.name=hw_43_Spring_Boot_REST
spring.thymeleaf.cache=false
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs